# setup for using github runners via https://cirun.io/
runners:
  - name: "aws-runner"
    # Cloud Provider: AWS
    cloud: "aws"
    # https://aws.amazon.com/ec2/instance-types/g4/
    instance_type: "g4ad.xlarge"
    # use Frankfurt region
    region: "eu-central-1"
    # use ubuntu 20.04
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-aws-runner"
