# cicd workflow for running tests with pytest
# needs to first install pdm, then install torch cpu manually and then install the package
# then run the tests

name: test (pdm install, cpu)

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pdm
        run: |
          python -m pip install pdm

      - name: Create venv
        run: |
          pdm venv create --with-pip
          pdm use --venv in-project

      - name: Install torch (CPU)
        run: |
          python -m pip install torch  --index-url https://download.pytorch.org/whl/cpu
          # check that the CPU version is installed
          python -c "import torch; assert torch.__version__.endswith('+gpu')"

      - name: Install package (including dev dependencies)
        run: |
          pdm install
          pdm install --dev

      - name: Run tests
        run: |
          pdm run pytest
