# cicd workflow for running tests with pytest
# needs to first install pdm, then install torch cpu manually and then install the package
# then run the tests

name: test (pip install, cpu)

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install torch (CPU)
        run: |
          python -m pip install torch  --index-url https://download.pytorch.org/whl/cpu

      - name: Install package (including dev dependencies)
        run: |
          python -m pip install .
          python -m pip install pytest

      - name: Print and check torch version
        run: |
          pdm run python -c "import torch; print(torch.__version__)"
          pdm run python -c "import torch; assert torch.__version__.endswith('+cpu')"

      - name: Run tests
        run: |
          python -m pytest
