# cicd workflow for running tests with pytest
# needs to first install pdm, then install torch cpu manually and then install the package
# then run the tests

name: test (pip install, cpu)

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install torch (CPU)
        run: |
          python -m pip install torch  --index-url https://download.pytorch.org/whl/cpu

      - name: Install package (including dev dependencies)
        run: |
          python -m pip install .
          # pip can't install from "dev" pdm group in pyproject.toml, should we put these requirements
          # for running tests in a seperate group? Using "dev" ensures that the these requirements aren't
          # included in build packages
          python -m pip install pytest pooch

      - name: Print and check torch version
        run: |
          python -c "import torch; print(torch.__version__)"
          python -c "import torch; assert torch.__version__.endswith('+cpu')"

      - name: Run tests
        run: |
          python -m pytest
