# cicd workflow for running tests with pytest
# needs to first install pdm, then install torch cpu manually and then install the package
# then run the tests

name: tests (cpu)

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pdm
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10"
          cache: true

      - name: Install torch (CPU)
        run: |
          python -m pip install torch  --index-url https://download.pytorch.org/whl/cpu

      - name: Install package (including dev dependencies)
        run: |
          pdm install
          pdm install --dev

      - name: Run tests
        run: |
          pdm run pytest
